services:
  app:
    build: .
    container_name: CAS_app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/CAS_db?schema=public
      - JWT_SECRET=Alae's_jwt_secret_key
      - NODE_ENV=development
      - PORT=5005
    ports:
      - "5005:5005"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CAS_db
    ports:
      - "5435:5432"  # Map port 5432 on both host and container
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
